# Generated by Django 5.2.8 on 2025-11-26 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais_origem', models.CharField(max_length=50)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artistas.genero', verbose_name='Gênero Musical')),
            ],
        ),
    ]
